### ISSUE TITLE
Analyzer tracking issue

### ISSUE THREAD

**Issue by chenlijun99** [MatMyfta/SistemiOperativi#1]
* [x] Mini protocollo di comunicazione (#4, #5)
* [x] Creazione processi (#2)
* [x] Counter
    * [x] Riconoscere e "spacchettare" cartelle (#6)
* [ ] Q
    * [ ] Lettura file e raccolta statistiche
